version: "3.9"

services:
  db:
    container_name: rssagg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rssagg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aggregator
    ports:
      - 5444:5432
